### ISSUE TITLE
Compilation fails on Raspberry Pi OS

### ISSUE THREAD

**Issue by FezzFest** [Opendigitalradio/ODR-EDI2EDI#1]
Compilation on Raspberry Pi OS 11.3 fails due to `undefined reference to '__atomic_load_8'`.
Explicitly adding libatomic with `./configure LIBS=-latomic` makes compilation work.

**Comment by mpbraendli** [comment]
Hi and thanks for the report! Can you check that the latest "next" commit fixes the issue? I've added a configure check. Thanks in advance.
